# Generated by Django 3.1.7 on 2021-06-02 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(default='TRUE', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category_parent',
            },
        ),
        migrations.CreateModel(
            name='CategoryChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/category')),
                ('status', models.CharField(default='TRUE', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('category_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categoryparent')),
            ],
            options={
                'db_table': 'category_child',
            },
        ),
    ]
